---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-consul-connect
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["get", "list", "create", "delete", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador-consul-connect
  namespace: ambassador
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambassador-consul-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-consul-connect
subjects:
  - kind: ServiceAccount
    name: ambassador-consul-connect
    namespace: ambassador
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: ambassador-consul
  namespace: ambassador
spec:
  hosts: []
  secret: ambassador-consul-connect
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-consul-connector
  namespace: ambassador
  annotations:
    a8r.io/owner: "Ambassador Labs"
    a8r.io/repository: github.com/datawire/ambassador
    a8r.io/description: "The Ambassador Edge Stack Consul Connect integration."
    a8r.io/documentation: https://www.getambassador.io/docs/edge-stack/latest/
    a8r.io/chat: http://a8r.io/Slack
    a8r.io/bugs: https://github.com/datawire/ambassador/issues
    a8r.io/support: https://www.getambassador.io/about-us/support/
    a8r.io/dependencies: "consul-server.default"
spec:
  ports:
  - name: ambassador-consul-connector
    port: 80
  selector:
    component: consul-connect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-consul-connect-integration
  namespace: ambassador
  labels:
    app: ambassador
    component: consul-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambassador
      component: consul-connect
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ambassador
        component: consul-connect
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      serviceAccountName: ambassador-consul-connect
      terminationGracePeriodSeconds: 0
      containers:
        - name: consul-connect-integration
          image: docker.io/datawire/aes:3.5.1
          command: [ "consul_connect_integration" ]
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 50Mi
          # volumeMounts:
          #   - name: consul-connect-ca
          #     mountPath: /etc/consul/connect-ca

          env:
            # Consul runs as a DaemonSet on each Node therefore we need to talk to the Host machine.
            # See: https://www.consul.io/docs/platform/k8s/run.html#architecture
            - name: _CONSUL_HOST
              value: "https://rp-uecxgqdp-dc1.private.consul.6f656329-aa6d-4777-b0e1-68927dac2aec.aws.hashicorp.cloud"
              # valueFrom:
              #   fieldRef:
              #     fieldPath: status.hostIP
            - name: _CONSUL_PORT
              value: "443"
            # - name: CONSUL_CACERT
            #   value: /etc/consul/connect-ca/tls.crt
            - name: CONSUL_HTTP_SSL
              value: "true"
            - name: CONSUL_HTTP_TOKEN
              value: "94985f91-11e6-22f4-5a2e-ffbc0cf97407"
            - name: _AMBASSADOR_TLS_SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      # volumes:
      #   - name: consul-connect-ca
      #     secret:
      #       secretName: consul-connect-ca
