---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-connect-mapping
spec:
  hostname: "*"
  prefix: /quote-connect/
  service: quote-connect-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
