
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quote-connect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-connect
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: quote-connect
  template:
    metadata:
      labels:
        app: quote-connect
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      serviceAccountName: quote-connect
      containers:
      - name: quote
        image: docker.io/datawire/quote:0.5.0
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: quote-connect
  annotations:
    a8r.io/description: "Quote service"
    a8r.io/owner: "No owner"
    a8r.io/chat: "#ambassador"
    a8r.io/bugs: "https://github.com/datawire/quote/issues"
    a8r.io/documentation: "https://github.com/datawire/quote/blob/master/README.md"
    a8r.io/repository: "https://github.com/datawire/quote"
    a8r.io/support: "http://a8r.io/Slack"
    a8r.io/runbook: "https://github.com/datawire/quote/blob/master/README.md"
    a8r.io/incidents: "https://github.com/datawire/quote/issues"
    a8r.io/dependencies: "None"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quote-connect
