apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: client3 ## The name of the partition containing the service
spec:
  services:
  - name: backend ## The name of the service you want to export
    consumers:
    - peer: dc1 ## The name of the peer that receives the service
  # - name: mesh-gateway
  #   consumers:
  #   - peer: rp-nfw8zsxf-dc1
