apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: client2
spec:
  services:
  - name: backend
    consumers:
    - partition: client1
  - name: mesh-gateway
    consumers:
    - partition: client1
