---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
spec:
  destination:
    name: frontend
  sources:
    - name: ingress-gateway
      action: allow
---
# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceIntentions
# metadata:
#   name: ingress-gateway
# spec:
#   destination:
#     name: ingress-gateway
#   sources:
#     - name: '*'
#       action: allow
